app_mode: "dev"
app_name: "local-adverts"
db_type: "mysql"
dsn: "localadverts:pass_to_localadverts@tcp(127.0.0.1:3306)/localadverts?parseTime=true"
jwt_signing_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
jwt_expiration: 120
recaptcha_key: ""
recaptcha_secret: ""
tls_key_path: "./data/certs/domain.key"
tls_cert_path: "./data/certs/chained.pem"
mail_smtphost: "smtp.xxxxx.xxxx"
mail_smtpport: "587"
mail_username: "xxxxxxxxxxxx@xxxxxxxxx.xxxx"
mail_password: "xxxxxxxxxx"
app_fqdn: "localhost"
http_entrypoint: "127.0.0.1:3000"
webserv_name: "local-adverts"
google_client_id: "xxxxxxxxxxxxxxx"
google_credential_file: "./data/credential.json"
google_redirect_path: "/oauth/googleuser"
app_secret_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
biz_name: "xxxxxxxxxx"
biz_shortname: "xxxxxxxxxxxx"
biz_email: ""
biz_phone: ""
biz_phone2: ""
biz_logo: "favicon.ico"
